-- =====================================================================
-- AI_FACTORY — ai_core + ai_vector RESTORE SCHEMA (reconstruction DDL)
-- =====================================================================
-- Source: live PostgreSQL READ-ONLY introspection (execution 1375,
--   workflow zWU3xchTGE4NnLQ4, SELECT-only). No DDL/DML was run on prod.
-- Purpose: recreate the AI_FACTORY schema on a FRESH local/standby DB.
-- WARNING: DO NOT run against the production database. Additive CREATE only.
-- Secrets (passwords, keys) are NOT part of schema and are NOT included.
-- Function BODIES are NOT reproduced verbatim (not exported from prod);
--   signatures + semantics are documented at the bottom. Re-export bodies
--   with pg_get_functiondef() before relying on exact behavior.
-- pgvector required: extension version observed = 0.8.2 ; vector(1536).
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS vector;      -- pgvector (>= 0.8.x for HNSW)

CREATE SCHEMA IF NOT EXISTS ai_core;
CREATE SCHEMA IF NOT EXISTS ai_vector;

CREATE TABLE IF NOT EXISTS ai_core.managers (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_code  text NOT NULL UNIQUE,
    name          text NOT NULL,
    domain        text,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','deprecated')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.agents (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_code       text NOT NULL UNIQUE,
    name             text NOT NULL,
    role             text,
    manager_id       bigint REFERENCES ai_core.managers(id),
    model            text,
    version          text,
    status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','disabled','deprecated')),
    memory_scope     text,
    max_concurrency  integer NOT NULL DEFAULT 1,
    current_load     integer NOT NULL DEFAULT 0,
    quality_score    numeric(4,3),
    success_rate     numeric(4,3),
    speed_score      numeric(4,3),
    cost_score       numeric(4,3),
    failure_rate     numeric(4,3),
    retry_count      integer NOT NULL DEFAULT 0,
    health_status    text NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('unknown','healthy','degraded','unhealthy')),
    heartbeat_at     timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    emergency_stopped     boolean NOT NULL DEFAULT false,
    emergency_reason      text,
    emergency_stopped_at  timestamptz
);
CREATE INDEX IF NOT EXISTS idx_agents_manager_id ON ai_core.agents(manager_id);
CREATE INDEX IF NOT EXISTS idx_agents_status     ON ai_core.agents(status);

CREATE TABLE IF NOT EXISTS ai_core.capabilities (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_code  text NOT NULL UNIQUE,
    name             text,
    description      text,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.agent_capabilities (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id       bigint NOT NULL REFERENCES ai_core.agents(id),
    capability_id  bigint NOT NULL REFERENCES ai_core.capabilities(id),
    proficiency    numeric(4,3),
    is_primary     boolean NOT NULL DEFAULT false,
    UNIQUE (agent_id, capability_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_capabilities_capability_id ON ai_core.agent_capabilities(capability_id);

CREATE TABLE IF NOT EXISTS ai_core.tool_permissions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint REFERENCES ai_core.agents(id),
    tool_code   text NOT NULL,
    allowed     boolean NOT NULL DEFAULT true,
    scope       text,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tool_permissions_agent_id ON ai_core.tool_permissions(agent_id);

CREATE TABLE IF NOT EXISTS ai_core.agent_versions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint NOT NULL REFERENCES ai_core.agents(id),
    version     text NOT NULL,
    model       text,
    prompt      text,
    config      jsonb,
    is_active   boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_versions_agent_id ON ai_core.agent_versions(agent_id);

CREATE TABLE IF NOT EXISTS ai_core.agent_health (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id       bigint NOT NULL REFERENCES ai_core.agents(id),
    health_status  text CHECK (health_status IS NULL OR health_status IN ('unknown','healthy','degraded','unhealthy')),
    heartbeat_at   timestamptz,
    details        jsonb,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_health_agent_id ON ai_core.agent_health(agent_id);

CREATE TABLE IF NOT EXISTS ai_core.agent_metrics (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     bigint NOT NULL REFERENCES ai_core.agents(id),
    metric       text NOT NULL,
    value        numeric,
    time_window  text,
    captured_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_metrics_agent_id ON ai_core.agent_metrics(agent_id);

CREATE TABLE IF NOT EXISTS ai_core.tasks (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_code              text UNIQUE,
    objective              text,
    status                 text NOT NULL DEFAULT 'created' CHECK (status IN ('created','planned','queued','assigned','running','qc','completed','failed','retrying','blocked','paused','cancelled','escalated')),
    priority               integer NOT NULL DEFAULT 5,
    required_capabilities  text[],
    parent_task_id         bigint REFERENCES ai_core.tasks(id),
    created_by             text,
    payload                jsonb,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    started_at             timestamptz,
    completed_at           timestamptz
);
CREATE INDEX IF NOT EXISTS idx_tasks_parent_task_id ON ai_core.tasks(parent_task_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status         ON ai_core.tasks(status);

CREATE TABLE IF NOT EXISTS ai_core.task_dependencies (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id              bigint NOT NULL REFERENCES ai_core.tasks(id),
    depends_on_task_id   bigint NOT NULL REFERENCES ai_core.tasks(id),
    UNIQUE (task_id, depends_on_task_id)
);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_depends_on ON ai_core.task_dependencies(depends_on_task_id);

CREATE TABLE IF NOT EXISTS ai_core.task_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     bigint NOT NULL REFERENCES ai_core.tasks(id),
    agent_id    bigint REFERENCES ai_core.agents(id),
    event_type  text NOT NULL,
    data        jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_events_task_id  ON ai_core.task_events(task_id);
CREATE INDEX IF NOT EXISTS idx_task_events_agent_id ON ai_core.task_events(agent_id);

CREATE TABLE IF NOT EXISTS ai_core.task_results (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id          bigint NOT NULL REFERENCES ai_core.tasks(id),
    agent_id         bigint REFERENCES ai_core.agents(id),
    capability_code  text,
    output           jsonb,
    status           text CHECK (status IS NULL OR status IN ('success','partial','failed','rejected')),
    score            numeric(4,3),
    created_at       timestamptz NOT NULL DEFAULT now(),
    execution_id     text
);
CREATE INDEX IF NOT EXISTS idx_task_results_task_id  ON ai_core.task_results(task_id);
CREATE INDEX IF NOT EXISTS idx_task_results_agent_id ON ai_core.task_results(agent_id);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_task_results_execution ON ai_core.task_results(execution_id) WHERE execution_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS ai_core.agent_leases (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     bigint NOT NULL REFERENCES ai_core.agents(id),
    task_id      bigint NOT NULL REFERENCES ai_core.tasks(id),
    status       text NOT NULL DEFAULT 'active' CHECK (status IN ('active','released','expired','revoked')),
    acquired_at  timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz,
    released_at  timestamptz,
    attempt      integer
);
CREATE INDEX IF NOT EXISTS idx_agent_leases_agent_id   ON ai_core.agent_leases(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_leases_task_id    ON ai_core.agent_leases(task_id);
CREATE INDEX IF NOT EXISTS idx_agent_leases_status     ON ai_core.agent_leases(status);
CREATE INDEX IF NOT EXISTS idx_agent_leases_expires_at ON ai_core.agent_leases(expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_agent_leases_active ON ai_core.agent_leases(task_id, agent_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS ai_core.qc_results (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         bigint REFERENCES ai_core.tasks(id),
    task_result_id  bigint REFERENCES ai_core.task_results(id),
    agent_id        bigint REFERENCES ai_core.agents(id),
    passed          boolean,
    score           numeric(4,3),
    issues          jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_qc_results_task_id        ON ai_core.qc_results(task_id);
CREATE INDEX IF NOT EXISTS idx_qc_results_agent_id       ON ai_core.qc_results(agent_id);
CREATE INDEX IF NOT EXISTS idx_qc_results_task_result_id ON ai_core.qc_results(task_result_id);

CREATE TABLE IF NOT EXISTS ai_core.decisions (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        bigint REFERENCES ai_core.tasks(id),
    decision_type  text, made_by text, rationale text, data jsonb,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_decisions_task_id ON ai_core.decisions(task_id);

CREATE TABLE IF NOT EXISTS ai_core.approvals (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       bigint REFERENCES ai_core.tasks(id),
    requested_by  text, approver text,
    status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
    reason        text, created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_approvals_task_id ON ai_core.approvals(task_id);

CREATE TABLE IF NOT EXISTS ai_core.learning_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint REFERENCES ai_core.agents(id),
    task_id     bigint REFERENCES ai_core.tasks(id),
    event_type  text, signal numeric, data jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_learning_events_agent_id ON ai_core.learning_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_task_id  ON ai_core.learning_events(task_id);

CREATE TABLE IF NOT EXISTS ai_core.experiments (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_code  text NOT NULL UNIQUE,
    name text, hypothesis text,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','running','completed','cancelled','archived')),
    config jsonb, created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, ended_at timestamptz
);

CREATE TABLE IF NOT EXISTS ai_core.experiment_results (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id  bigint NOT NULL REFERENCES ai_core.experiments(id),
    variant text, metric text, value numeric, data jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_experiment_results_experiment_id ON ai_core.experiment_results(experiment_id);

CREATE TABLE IF NOT EXISTS ai_core.knowledge_sources (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code  text NOT NULL UNIQUE,
    title text, type text, uri text,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','deprecated')),
    metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.memory (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope       text NOT NULL, owner_code text, key text, content text, metadata jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_memory_scope_owner_key ON ai_core.memory(scope, owner_code, key);

CREATE TABLE IF NOT EXISTS ai_core.system_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL UNIQUE, value jsonb, description text, updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.system_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL UNIQUE, value jsonb, updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.system_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','error','critical')),
    source text, data jsonb, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.system_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type text NOT NULL,
    severity text CHECK (severity IS NULL OR severity IN ('info','warning','error','critical')),
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','resolved','closed')),
    message text, data jsonb, created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);

CREATE TABLE IF NOT EXISTS ai_core.system_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_type text, state jsonb, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.recovery_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_type text, affected_entity text, action_taken text,
    status text CHECK (status IS NULL OR status IN ('pending','in_progress','resolved','failed')),
    data jsonb, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_core.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor text, action text NOT NULL, entity_type text, entity_id text,
    before jsonb, after jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
-- POLICY: audit_logs is APPEND-ONLY (no UPDATE/DELETE granted to app roles).

CREATE TABLE IF NOT EXISTS ai_core.workflows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_code text NOT NULL UNIQUE, name text, n8n_workflow_id text, type text,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','deprecated')),
    config jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_vector.knowledge_vectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint REFERENCES ai_core.knowledge_sources(id),
    chunk_index integer, content text, embedding vector(1536), metadata jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_vectors_source_id ON ai_vector.knowledge_vectors(source_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_vectors_embedding_hnsw ON ai_vector.knowledge_vectors USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS ai_vector.memory_vectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope text, owner_code text, content text, embedding vector(1536), metadata jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_memory_vectors_embedding_hnsw ON ai_vector.memory_vectors USING hnsw (embedding vector_cosine_ops);

CREATE OR REPLACE FUNCTION ai_core.set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['agents','knowledge_sources','managers','memory','system_config','system_state','tasks','workflows']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_set_updated_at ON ai_core.%I; CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON ai_core.%I FOR EACH ROW EXECUTE FUNCTION ai_core.set_updated_at();', t, t);
  END LOOP;
END $$;

-- =====================================================================
-- FUNCTIONS — signatures & semantics ONLY (bodies NOT exported from prod)
-- Re-export exact bodies with: SELECT pg_get_functiondef(oid) FROM pg_proc ...
-- ai_core.reserve_agent(p_task_id, p_agent_id, p_ttl_seconds=30, p_attempt) RETURNS jsonb
--   SOLE queued->assigned lease authority. Inserts agent_leases(active), updates
--   tasks(queued->assigned)+agents, inserts task_events. FOR UPDATE locks. Idempotent.
-- ai_core.release_lease(...) / ai_core.expire_leases(...) -> lease lifecycle + task_events
-- ai_core.set_agent_emergency_stop(p_agent_code,p_reason,p_actor) actor IN ('human','governor')
-- ai_core.clear_agent_emergency_stop(p_agent_code,p_actor) actor guard as above
-- In prod: owner=postgres, SECURITY INVOKER, PUBLIC EXECUTE. GAP-TOP-005 recommends
-- recreating the 5 writing functions as SECURITY DEFINER owned by af_func_owner with
-- PUBLIC EXECUTE revoked. Apply during a controlled migration, not here.
-- =====================================================================
